project_id = "ochulsnvnqcbzqnlkazu"

[functions.analyze-ito]
verify_jwt = false

[functions.analyze-crossed-line]
verify_jwt = false

[functions.analyze-someone-crossed]
verify_jwt = false

[functions.crossed-line-followup]
verify_jwt = false

[functions.ito-followup]
verify_jwt = false

[functions.analyze-language]
verify_jwt = false

[functions.eval-ito]
verify_jwt = false
